project_id = "xppkrgxuaisiqtjuejsb"

[functions.ai-chat]
verify_jwt = false

[functions.savings-analysis]
verify_jwt = false

[functions.risk-analysis]
verify_jwt = false

[functions.pluggy-auth]
verify_jwt = false

[functions.pluggy-webhook]
verify_jwt = false

[functions.pluggy-sync]
verify_jwt = false
